### ISSUE TITLE
dull_colours

### ISSUE THREAD

**Issue by MMunglah** [MMunglah/RainbowPoem#1]
- [x] 1. Create a 'dull' branch for the work.
- [x] 2. Add beige to the poem.
- [x] 3. Add ivory to the poem.
- [x] 4. Add khaki.
- [x] 5. Take out all those nasty primary colours.

**Comment by MMunglah** [comment]
Made a dull branch.

**Comment by MMunglah** [comment]
Gray is a cool, neutral, and balanced colour. The colour grey is an emotionless, moody colour that is typically associated with meanings of dull, dirty, and dingy, as well as formal, conservative, and sophisticated.

The colour grey is a timeless and practical colour that is often associated with loss or depression. Dark, charcoal grey communicates some of the strength and mystery of black. It is a sophisticated colour that lacks the negativity of the colour black. Light greys can carry some of the attributes of the colour white.

The grey colour affects the mind and body by causing unsettling feelings. Light greys are feminine in nature, while dark greys are masculine in nature. 

-( https://www.bourncreative.com/meaning-of-the-color-grey/ )
![image](https://user-images.githubusercontent.com/57633694/73754983-38e0ab00-475d-11ea-8bfb-ae23f1cb35f8.png)

**Comment by MMunglah** [comment]
Fixed all the issues.

**Comment by osmart** [comment]
Good stuff - subtasks setup and clicked. Commit messages have the issue number

The only thing is that all your commits are 'verified'  unless you are clever with signing this means that the change has been done on GitHub. Will need to do branch commits from a local repo in the end.
